version: "3.9"
services:
  db:
    container_name: db_container
    image: postgres:15.2-alpine
    volumes:
      - ./docker/initdb:/docker-entrypoint-initdb.d
      - ./docker/postgres/conf:/var/lib/lib/postgresql/data
      - ./db-data:/var/lib/postgresql/data/ #needed to specify where to create the database directory
    env_file:
      - ./docker/database.dev.env
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge