spring:
  flyway:
    locations: classpath:db/migration
    schemas:
      - dbuser
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: dbuser
    password: password
  jpa:
    properties:
      hibernate:
        defaultSchema: dbuser #specify the default schema